version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadence-backend
    env_file:
      - .env
    ports:
      - "8000:8000"

  user:
    build:
      context: .
      dockerfile: frontend/user/Dockerfile
    container_name: cadence-user
    env_file:
      - ./frontend/user/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  admin:
    build:
      context: .
      dockerfile: frontend/admin/Dockerfile
    container_name: cadence-admin
    ports:
      - "3001:3001"
    depends_on:
      - backend